# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
FitSSModel <- function(y, y_counts, X, groups, n_groups, method, alpha_prior, W, phi, correction, intercept, burnin, samples, thinning, verbose, progress_every, spike_optim, update_spike_every, sample_delta, sample_gamma, sample_d, nu_2_init, alpha_init, delta_init, rho_init, tau_2_delta_init, psi_2_init, eta_init, d_init, gamma_init, d_groups_init, gamma_groups_init, P_gamma, P_d, nu_2_alpha, nu_2_beta, tau_s_alpha, sigma_2_alpha_spike, sigma_2_alpha_slab, gamma_prior, a_gamma, b_gamma, a_d, b_d, nu_j, xi, lambda_alpha, grid_prior_values, rho_prior_probs, tau_2_delta_alpha, tau_2_delta_beta, psi_2_alpha, psi_2_beta, sigma_2_j, sigma_2_j_s, prior_d) {
    .Call(`_DreameSpase_FitSSModel`, y, y_counts, X, groups, n_groups, method, alpha_prior, W, phi, correction, intercept, burnin, samples, thinning, verbose, progress_every, spike_optim, update_spike_every, sample_delta, sample_gamma, sample_d, nu_2_init, alpha_init, delta_init, rho_init, tau_2_delta_init, psi_2_init, eta_init, d_init, gamma_init, d_groups_init, gamma_groups_init, P_gamma, P_d, nu_2_alpha, nu_2_beta, tau_s_alpha, sigma_2_alpha_spike, sigma_2_alpha_slab, gamma_prior, a_gamma, b_gamma, a_d, b_d, nu_j, xi, lambda_alpha, grid_prior_values, rho_prior_probs, tau_2_delta_alpha, tau_2_delta_beta, psi_2_alpha, psi_2_beta, sigma_2_j, sigma_2_j_s, prior_d)
}

